[project]
name = "session-7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.8.0.post1",
    "fastapi>=0.115.12",
    "google-genai>=1.13.0",
    "markitdown>=0.1.1",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "uvicorn>=0.33.0",
]
